# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Continuous integration

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  setup-yarn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use NodeJS 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: 'yarn'
      - name: Caching node_modules
        uses: actions/cache@v3
        id: cache-node-module
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        if: steps.cache-node-module.outputs.cache-hit != 'true'
        run: yarn install --immutable

  build:
    needs:
      - setup-yarn

    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use NodeJS 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: 'yarn'
      - name: Uncaching node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn rw build

  circular-dependencies:
    needs:
      - setup-yarn

    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use NodeJS 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: 'yarn'
      - name: Uncaching node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Check api circular dependencies
        run: yarn madge -c -s --extensions ts --ts-config api/tsconfig.json api
      - name: Check web circular dependencies
        run: yarn madge -c -s --extensions ts,tsx --ts-config web/tsconfig.json web

  test:
    needs:
      - setup-yarn

    runs-on: ubuntu-latest
    services:
      test-db:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: jintuslive-test
          POSTGRES_DB: billard_training_test
        ports:
          - 5433:5432
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use NodeJS 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: 'yarn'
      - name: Uncaching node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn rw test --watch false

  lint:
    needs:
      - setup-yarn

    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use NodeJS 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17
          cache: 'yarn'
      - name: Uncaching node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - run: yarn rw lint
